#!/usr/bin/env bash

. ../theme || exit

{
cat << 'EOF'
                   /\
                 /   |            /\
               /    /            |&&|
             /      |            \&&/
           /          \          | |
         /              \        | |
       <__________________>     | | 
            |  ^  ^  |           | |
            |  ,,,,  |          | | 
             \______/          __| |
             /      \         /  | |
           / \ \   / /\     /   _| |
      __ /    \ \ / /   \ /    / | |
     /  |      \ \ /         /    | |
    /  |        \ \        /     | |
   /  /|         \ \      |      | |
EOF
} | while IFS= read -r line; do
  echo "${BOLD}${line}${RESET}"
done
