#!/usr/bin/env bash

. ../theme || exit
. ../tools/repeat-char || exit

# Header with logo and basic info
./make-header
echo

# Experience content with proper padding
padding=5
padding_str=$(repeat-char ' ' "$padding")

printf "%s${BOLD}My Experience${RESET}\n\n" "$padding_str"

printf "%s${DARKERBLUE}${BOLD}Azabu Insights${RESET} ${GRAY300}(June 2025 - Present)${RESET}\n" "$padding_str"
printf "%s${LIGHTERBLUE}Software Engineer / Consultant${RESET}\n" "$padding_str"
printf "\n"

printf "%s${DARKERBLUE}${BOLD}Text Marley${RESET} ${GRAY300}(January 2025 - Present)${RESET}\n" "$padding_str"
printf "%s${LIGHTERBLUE}Co-founder / Backend Engineer${RESET}\n" "$padding_str"
printf "\n"

printf "%s${DARKERBLUE}${BOLD}BU Finance and Investment Club${RESET} ${GRAY300}(September 2023 - December 2024)${RESET}\n" "$padding_str"
printf "%s${LIGHTERBLUE}Senior Quantitative Developer${RESET}\n" "$padding_str"

printf "\n"

printf "%s${BOLD}Type this command to download everything in a PDF:${RESET} ${LIGHTERBLUE}\$ curl -o Liu_Resume.pdf ${DARKERBLUE}eliu.sh/resume${RESET}\n" "$padding_str"

echo
