#!/usr/bin/env bash

. ../theme || exit
. ../tools/repeat-char || exit

# Store the figure in an array
mapfile -t FIGURE < <(./make-figure)

# Store the box in an array
mapfile -t BOX < <(
  {
    printf "To see the full menu options,\n"
    printf "enter this in your command prompt:\n"
    printf "\n"
    printf "${LIGHTERBLUE}\$ curl${RESET} ${DARKERBLUE}eliu.sh/menu${RESET}"
  } | ../tools/box -vp 1 -hp 1
)

# Add empty lines at the beginning to move box down
BOX=("" "" "" "" "${BOX[@]}")

# Get the max number of lines between figure and box
num_figure=${#FIGURE[@]}
num_box=${#BOX[@]}
max_lines=$(( num_figure > num_box ? num_figure : num_box ))

# Get width of a figure line (stripped of ANSI)
figure_width=$(echo "${FIGURE[0]}" | ../tools/strip-ansi)
figure_len=${#figure_width}

# Print line-by-line
for ((i = 0; i < max_lines; i++)); do
  line1="${FIGURE[i]}"
  line2="${BOX[i]}"

  # If figure line is missing, pad it
  if [[ -z $line1 ]]; then
    line1=$(../tools/repeat-char ' ' "$figure_len")
  fi

  echo "$line1      $line2"  # increased spacing to move box right
done
