#!/usr/bin/env bash

. ../theme || exit
. ../tools/repeat-char || exit

# Header with logo and basic info
./make-header
echo

# Experience content with proper padding
padding=5
padding_str=$(repeat-char ' ' "$padding")

printf "%sMy Experience\n\n" "$padding_str"

printf "%s${DARKERBLUE}Azabu Insights${RESET} ${GRAY300}(June 2025 - Present)${RESET}\n" "$padding_str"
printf "%s${LIGHTERBLUE}Software Engineer / Consultant${RESET}\n" "$padding_str"
printf "\n"

printf "%s${DARKERBLUE}Text Marley${RESET} ${GRAY300}(January 2025 - Present)${RESET}\n" "$padding_str"
printf "%s${LIGHTERBLUE}Co-founder / Backend Engineer${RESET}\n" "$padding_str"
printf "\n"

printf "%s${DARKERBLUE}BU Finance and Investment Club${RESET} ${GRAY300}(September 2023 - December 2024)${RESET}\n" "$padding_str"
printf "%s${LIGHTERBLUE}Senior Quantitative Developer${RESET}\n" "$padding_str"

echo
