#!/usr/bin/env bash

. .././theme || exit
. .././tools/repeat-char || exit

padding=5
padding_str=$(repeat-char ' ' "$padding")

# Read logo lines into array (compatible with older bash)
logo=()
while IFS= read -r line; do
    logo+=("$line")
done < <(./make-logo)

description=(
	""
	"${WHITE} Evan Liu${RESET}"
	"${WHITE} Boston University, Class of 2027${RESET}"
	"${WHITE} Check out my main website: ${DARKERBLUE}https://evanpliu.com${RESET}"
  ""
  "${WHITE} Source code: ${DARKERBLUE}https://github.com/evanl23/eliu.sh${RESET}"
)

len=${#logo[@]}

for ((i = 0; i < len; i++)); do
	logo_line=${logo[i]}
	desc_line=${description[i]}

	printf "%s%s%s\n" "$logo_line" "$padding_str" "$desc_line"
done

echo
